<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>demo-playwright-c-sharp</AssemblyName>
    <RootNamespace>Demo</RootNamespace>
    <Version>1.0.0</Version>
    <Authors>Joel Parker Henderson</Authors>
    <Description>Demo Playwright C#</Description>
    <RepositoryUrl>https://github.com/testingexamples/demo-playwright-c-sharp/</RepositoryUrl>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.*" />
  </ItemGroup>

</Project>
